language: python
python:
    - "2.7"
addons:
    apt:
        packages:
            - libblas-dev
            - liblapack-dev 
install:
    - pip install -e .
script:
    - cd seekpath && python test_paths_hpkot.py
    - cd seekpath/hpkot && python test_get_primitive.py
## Commenting the next two because they require AiiDA
#    - python test_aiida_conversion.py
#    - python test_aiida_wrappers.py
