language: python
python:
    - "2.7"
notifications:
    email:
        on_success: never
        on_failure: always
addons:
    apt:
        packages:
            - gfortran
            - libblas-dev
            - liblapack-dev 
install:
    - pip install -e .
script:
    - cd seekpath && python test_paths_hpkot.py
# I go in a subfolder
    - cd hpkot && python test_get_primitive.py
## Commenting the next two because they require AiiDA
#    - python test_aiida_conversion.py
#    - python test_aiida_wrappers.py
