language: python
python:
    - "2.7"
    - "3.5"
notifications:
    email:
        on_success: never
        on_failure: always
addons:
    apt:
        packages:
            - gfortran
            - libblas-dev
            - liblapack-dev 
install:
    - pip install --only-binary scipy -r optional-requirements.txt
    - pip install -e .
script:
    - python run_tests.py

